[package]
name = "infinite_image_browsing"
version = "1.9.0"
description = "Shiying local media library"
authors = ["zanllp", "hhhxxxddd"]
license = "MIT"
repository = "https://github.com/hhhxxxddd/infinite-image-browsing"
edition = "2021"


[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.6", features = ["devtools"] }
tauri-plugin-dialog = "2.7.3"
tauri-plugin-shell = "2.3.6"
tauri-plugin-drag = "=2.1.1"
tauri-plugin-windows-file-drop = "=0.1.0"
serde = { version = "1.0.229", features = ["derive"] }
chrono = "0.4.45"

[features]
custom-protocol = ["tauri/custom-protocol"]
