"""Storage usage and explicitly disposable files; never clear persistent project data."""

import os
import threading
import time
from collections import Counter
from contextlib import contextmanager
from pathlib import Path

from omnigallery.storage.filesystem import checked_path, is_link
from omnigallery.storage.layout import DIRECTORIES

_active = Counter()
_lock = threading.RLock()
_started = time.time()


@contextmanager
def use_cache(path):
    key = os.path.normcase(os.path.abspath(path))
    with _lock:
        _active[key] += 1
    try:
        yield
    finally:
        with _lock:
            _active[key] -= 1
            if not _active[key]:
                del _active[key]


def _walk(root):
    """Skip inaccessible/link entries and report them, without following their targets."""
    try:
        checked_path(root)
        if not root.exists():
            return
        with os.scandir(root) as entries:
            for entry in entries:
                path = Path(entry.path)
                if is_link(path):
                    yield path, None
                elif entry.is_dir(follow_symlinks=False):
                    yield from _walk(path)
                elif entry.is_file(follow_symlinks=False):
                    try:
                        yield path, entry.stat(follow_symlinks=False)
                    except OSError:
                        yield path, None
    except (OSError, ValueError):
        yield root, None


def _disposable(root, path, info):
    relative = path.relative_to(root)
    parts = relative.parts
    if not info:
        return False
    # Only leftovers from a previous process are eligible; running jobs can use tmp freely.
    if parts[0] == "tmp":
        return info.st_mtime < _started and info.st_ctime < _started
    if parts[:2] != ("cache", "thumbnails"):
        return False
    if "video_cover" in parts:
        # Older covers may be user-selected. Only covers explicitly generated by us are disposable.
        return path.name == "cover.webp" and (path.parent / ".generated").is_file()
    return path.suffix == ".webp" or (
        path.suffix == ".tmp" and info.st_mtime < _started and info.st_ctime < _started
    )


def usage(root: Path):
    rows = []
    total = reclaimable = skipped = 0
    for name, label in DIRECTORIES.items():
        size = files = available = inaccessible = 0
        for path, info in _walk(root / name):
            if info is None:
                inaccessible += 1
                continue
            size += info.st_size
            files += 1
            with _lock:
                busy = bool(_active[os.path.normcase(os.path.abspath(path))])
            if not busy and _disposable(root, path, info):
                available += info.st_size
        rows.append(
            {
                "name": name,
                "label": label,
                "bytes": size,
                "files": files,
                "reclaimable_bytes": available,
                "skipped": inaccessible,
            }
        )
        total += size
        reclaimable += available
        skipped += inaccessible
    return {
        "directory": str(root),
        "total_bytes": total,
        "reclaimable_bytes": reclaimable,
        "skipped": skipped,
        "categories": rows,
    }


def clear_cache(root: Path):
    root = checked_path(root)
    released = removed = skipped = 0
    for name in ("cache/thumbnails", "tmp"):
        for path, info in _walk(root / name):
            if info is None:
                skipped += 1
                continue
            if not _disposable(root, path, info):
                continue
            try:
                with _lock:
                    if _active[os.path.normcase(os.path.abspath(path))]:
                        skipped += 1
                        continue
                    safe = checked_path(path)
                    if root not in safe.parents:
                        raise ValueError("清理路径超出应用数据目录")
                    current = safe.stat()
                    if (current.st_mtime_ns, current.st_size) != (
                        info.st_mtime_ns,
                        info.st_size,
                    ) or (info.st_ino and current.st_ino != info.st_ino):
                        skipped += 1
                        continue
                    safe.unlink()
                    released += info.st_size
                    removed += 1
            except (OSError, ValueError):
                skipped += 1
    return {"released_bytes": released, "removed_files": removed, "skipped": skipped}
