[package]
name = "omnigallery"
version = "1.9.0"
description = "OmniGallery local media library"
authors = ["zanllp", "hhhxxxddd"]
license = "MIT"
repository = "https://github.com/hhhxxxddd/infinite-image-browsing"
edition = "2021"


[build-dependencies]
tauri-build = { version = "2.7.0", features = [] }

[dependencies]
tauri = { version = "2.12.0", features = ["devtools"] }
tauri-plugin-dialog = "2.8.0"
tauri-plugin-shell = "2.4.0"
tauri-plugin-windows-file-drop = "=0.1.0"
serde = { version = "1.0.229", features = ["derive"] }
chrono = "0.4.45"
uuid = { version = "1", features = ["v4"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
